### ISSUE TITLE
OPENAI回调失败--bug fixed 

### ISSUE THREAD

**Issue by G244** [sytpb/chatgpt-wework-robot#1]
OPENAI回调失败

**Comment by sytpb** [comment]
是按文档 顺序走的吗？  我昨天还部了一套。

**Comment by G244** [comment]
是，今天才弄得呢

**Comment by G244** [comment]
端口号6060对吗

**Comment by G244** [comment]
![image](https://user-images.githubusercontent.com/58899275/233560475-15acfb00-040d-418c-8417-298920cb5bc8.png)

**Comment by sytpb** [comment]
先确认下服务是否正确安装， 
![image](https://user-images.githubusercontent.com/12178686/233582429-97f9f0f1-ab8d-4a31-9c16-283a4c20a7cd.png)
看 到这些信息，代表服务部署成功。

**Comment by G244** [comment]
![image](https://user-images.githubusercontent.com/58899275/233584241-b9fbf356-b451-4a68-9098-2a6cc2c977e7.png)
有的，但是没有最后一句your service is live

**Comment by sytpb** [comment]
哦，小问题，部署失败了，
![image](https://user-images.githubusercontent.com/12178686/233585325-f35e1bbf-277a-40ba-a9bb-dc00d1f9b1ef.png)
手动重部一下就好了， 点这个按钮，选第一项，deploy latest commit .

**Comment by G244** [comment]
![image](https://user-images.githubusercontent.com/58899275/233589918-7f695d50-764f-40d2-88f7-669326011813.png)
好像 不行

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/233591178-450decc8-c0cf-465e-8b1a-0948f4e40e77.png)
这个问题我也遇到过，你试下第三项，重来一次。

**Comment by sytpb** [comment]
抱歉， yaml 文件health check 配置有个小问题，造成deploy 最后会失败。 现已修复！
![image](https://user-images.githubusercontent.com/12178686/233615803-2c0c8251-9da9-4f2f-b441-662c7288eedd.png)
重新执行 Deploy latest commit 即可。已验证。

**Comment by G244** [comment]
部署是可以了，但还是回调失败https://wework-chatgpt-f6qc.onrender.com 会不会是你的yaml少了secret配置

**Comment by sytpb** [comment]
贴下日志，我看下。

**Comment by G244** [comment]
![image](https://user-images.githubusercontent.com/58899275/233643718-cf459b4a-5982-4d43-b713-577bc59aa9f8.png)
日志好像没啥

**Comment by sytpb** [comment]
知道了， https://wework-chatgpt-f6qc.onrender.com/message    后面加上/message ,文档里忘了这个细节了。    保存一下不成功，多点几下，应该没问题了。

**Comment by G244** [comment]
可以了！

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/233655826-7e713622-c0bf-45bb-b0be-ed33d4606135.png)

![image](https://user-images.githubusercontent.com/12178686/233655380-abc03fe0-82c3-44fa-bf7c-87c33bd6108b.png)

我的疏忽 ， yaml 少配一个变量， SECRET ，你手动添加一个，填上值后，保存即可。 
此问题已经修复。

**Comment by sytpb** [comment]
记录解决过程：问题在于， yaml 文件health check path路径 ,server 端增加回复响应， 另外发现yaml 少一个SECRET variable .

**Comment by sytpb** [comment]
记录解决过程：问题在于， yaml 文件health check path路径 ,server 端增加回复响应， 另外发现yaml 少一个SECRET variable .

**Comment by cxhjmfl** [comment]
Apr 24 07:24:33 PM  ==> Starting service with 'node app.js'
Apr 24 07:24:37 PM  file:///opt/render/project/src/comm/debug.js:10
Apr 24 07:24:37 PM        Error.captureStackTrace(err, arguments.callee.caller);
Apr 24 07:24:37 PM                                               ^
Apr 24 07:24:37 PM  
Apr 24 07:24:37 PM  [get (file:///opt/render/project/src/comm/debug.js:10:46),get (file:///opt/render/project/src/comm/debug.js:29:18),Function.log (file:///opt/render/project/src/comm/debug.js:40:25),file:///opt/render/project/src/route/conversation.js:7:7,ModuleJob.run (internal/modules/esm/module_job.js:152:23),async Loader.import (internal/modules/esm/loader.js:177:24),async Object.loadESM (internal/process/esm_loader.js:68:5)]

**Comment by sytpb** [comment]
@cxhjmfl 更新版本引起此问题，已修复。
