### ISSUE TITLE
域名已经无法调用了

### ISSUE THREAD

**Issue by robertlee33** [sytpb/chatgpt-wework-robot#10]
最后第二步 填写域名的时候，企业微信提示“域名主体校验未通过，需配置备案主体与当前企业主体相同或有关联关系的域名 配置指引”

**Comment by aierdiao** [comment]
同，无法保存从render获取的网址，提示和楼上相同，配置可信ip时也无法直接配置

**Comment by sytpb** [comment]
这情况需要自己的域名。

**Comment by sytpb** [comment]
@sharkbear212 贴个图看下，“配置可信ip时也无法直接配置”

**Comment by sytpb** [comment]
域名主体校验未通过--这是企业微信安全检测，认证过的企业需要自己的域名，域名解析CNAME指向此文档中生成的域名即可。
