### ISSUE TITLE
正常运行后，不返回回复

### ISSUE THREAD

**Issue by xiaoxin2016** [sytpb/chatgpt-wework-robot#11]
问题同：https://github.com/sytpb/chatgpt-wework-robot/issues/8

log里面是有回复的，但是没有办法通过企业微信发出。

![IMG_2833](https://user-images.githubusercontent.com/24978668/234828231-aa5f8c6d-93f6-433c-a429-7a1ba2584968.jpg)

![image](https://user-images.githubusercontent.com/24978668/234827943-2d7b37c7-61f4-4b08-9d73-b9138e7c0b39.png)

但我重新部署不能解决这个问题。

**Comment by sytpb** [comment]
![f3351952732f4705d729087dca329ec](https://user-images.githubusercontent.com/12178686/235142766-0dcdda84-0ea7-4151-85e3-d16eef1934e3.png)

没有配置可信IP。
