### ISSUE TITLE
显示“正在生成回答”，log里提示<conversation.js:29>false

### ISSUE THREAD

**Issue by elizzzzzz** [sytpb/chatgpt-wework-robot#12]
May 6 12:22:10 AM    Longitude: [ '121.512' ],
May 6 12:22:10 AM    Precision: [ '31' ],
May 6 12:22:10 AM    AppType: [ 'wxwork' ]
May 6 12:22:10 AM  }
May 6 12:22:10 AM  <conversation.js:29> false
May 6 12:22:10 AM  <conversation.js:16> ------------------------ROUTER MSG [CONVERSATION]-------------------------
May 6 12:22:10 AM  <conversation.js:23> event [Object: null prototype] {

**Comment by sytpb** [comment]
看这日志，修改了代码？chat 对象没有创建成功， 检查下哪里改出了问题。
