### ISSUE TITLE
显示open-ai错误

### ISSUE THREAD

**Issue by jingjining1** [sytpb/chatgpt-wework-robot#13]
![image](https://github.com/sytpb/chatgpt-wework-robot/assets/133858747/ad644120-f3d1-4530-be16-588f0bf06be1)

**Comment by Dlian-Zero** [comment]
OpenAI happen error!
May 17 07:49:26 PM  {
May 17 07:49:26 PM    message: 'You exceeded your current quota, please check your plan and billing details.',
May 17 07:49:26 PM    type: 'insufficient_quota',
May 17 07:49:26 PM    param: null,
May 17 07:49:26 PM    code: null
May 17 07:49:26 PM  }

**Comment by sytpb** [comment]
免费的额度用完了。

**Comment by sytpb** [comment]
继续用得给openai 充值了。

**Comment by Dlian-Zero** [comment]
> 继续用得给openai 充值了。

可是我这个月没用过openai api接口啊

**Comment by Dlian-Zero** [comment]
> > 继续用得给openai 充值了。
> 
> 可是我这个月没用过openai api接口啊

好吧，过期了

**Comment by sytpb** [comment]
哦，很有可能是你的这个key过期了，重新生成一个就可以了。进到你账号里看下。

**Comment by Dlian-Zero** [comment]
![S$MD7FU@T R1K3_$LIXS{2L](https://github.com/sytpb/chatgpt-wework-robot/assets/52018129/9e513984-2087-4e38-b764-1551d1d26259)
过期了，要续费

**Comment by sytpb** [comment]
好吧， 18刀想用完，还有点难其实。
