### ISSUE TITLE
OpenAI happen error!

### ISSUE THREAD

**Issue by wogoshu** [sytpb/chatgpt-wework-robot#14]
![image](https://github.com/sytpb/chatgpt-wework-robot/assets/43874020/619d9b35-4cd7-4a58-982f-799e43aaff88)

**Comment by wogoshu** [comment]
给个微信群联系方式吗，二维码过期了

**Comment by sytpb** [comment]
请检查参数是否配置正确，
![fb7652e2dc7af1878ef8a229ece2809](https://github.com/sytpb/chatgpt-wework-robot/assets/12178686/4ae99fba-1e8e-48e9-8023-a6f44cc0587f)

**Comment by wogoshu** [comment]
![图片](https://github.com/sytpb/chatgpt-wework-robot/assets/43874020/cf8d0736-221f-4bac-a3fe-f5e5c5a38abd)

多个key怎么填呢？谢谢了！

**Comment by sytpb** [comment]
![image](https://github.com/sytpb/chatgpt-wework-robot/assets/12178686/38614568-e4e9-4fa0-9368-4400d7c04dc3)

**Comment by wogoshu** [comment]
我现在有多个key,我想填到render里面，用逗号隔开吗？还是？

**Comment by wogoshu** [comment]
render页面填写多个key用逗号隔开报错了

**Comment by sytpb** [comment]
不能多个，只填一个。

**Comment by LHTon** [comment]
> ![image](https://user-images.githubusercontent.com/43874020/239800161-619d9b35-4cd7-4a58-982f-799e43aaff88.png)

你好！请问这个问题解决了吗？
