### ISSUE TITLE
OpenAI Happen ERROR的问题

### ISSUE THREAD

**Issue by Onining** [sytpb/chatgpt-wework-robot#15]
![1](https://github.com/sytpb/chatgpt-wework-robot/assets/43145076/0266625e-64fe-48ce-95cf-e1fd6bb39c4f)
根据前面的回答，检查了参数设置，没有发现异常，不清楚是怎么回事？特此请教。
注：二维码过期了

**Comment by Onining** [comment]
自我排错：1.不知是否和GPT API接口需要计费有关，正在排查

**Comment by sytpb** [comment]
如果是免费的api key 查下是否已经到期了，或者是额度用完了。

**Comment by Onining** [comment]
未到期，额度还剩得多

**Comment by sytpb** [comment]
贴图上来

**Comment by sytpb** [comment]
同 #13
