### ISSUE TITLE
CNAME定向域名-openapi回调地址请求不通过

### ISSUE THREAD

**Issue by zapp926** [sytpb/chatgpt-wework-robot#16]
![Screen Shot 2023-06-12 at 4 49 01 PM](https://github.com/sytpb/chatgpt-wework-robot/assets/35788274/72c0b734-3875-43ef-bc39-4618bef7af9d)

服务已经开启，并将访问地址【https://wework-chatgpt-zckl.onrender.com】通过CNAME定向到【公司二级域名】，CNAME配置完毕后，在「公司二级域名后面」添加「/messa」，提示【openapi回调地址请求不通过】。

参数已经对照着「Readme问题汇总」部分核对过了，是「https」的域名，后面也加上了「/message」。端口号试过6060、443两个。

**Comment by sytpb** [comment]
![image](https://github.com/sytpb/chatgpt-wework-robot/assets/12178686/bab10346-376a-4cfb-8ed5-e2f4c9877f11)


https://render.com/docs/custom-domains
按照这里配置。

**Comment by zapp926** [comment]
![Screen Shot 2023-06-13 at 1 56 00 PM](https://github.com/sytpb/chatgpt-wework-robot/assets/35788274/aa1c263b-de02-414d-a4ed-608c799161a0)
好的，非常感谢，域名部分已经配置完毕。可信IP也设置完毕，但是log这里，一直是未定义Token，请问原因是？谢谢🙏。

**Comment by sytpb** [comment]
这是获取Accesstoken 失败了， 请检查CORPID SECRET 这两个参数。

**Comment by zapp926** [comment]
好的，确实是在复制的时候，有个参数多了一个字母。现在TOKEN问题解决了。

不过还是没能成功，给Bot发消息没有任何的回复，连「生成回答」都没有出现。

企业微信端的「域名」和「可信IP」都已经部署了。所以收不到消息的话，是不是还是「可信IP」的问题？？？谢谢

不知道和域名的证书这部分有没有什么关系？？？

<img width="1371" alt="Screen Shot 2023-06-14 at 9 55 33 AM" src="https://github.com/sytpb/chatgpt-wework-robot/assets/35788274/cfd8b729-95ee-48e2-8772-0d6491b98435">
<img width="1320" alt="Screen Shot 2023-06-14 at 9 55 42 AM" src="https://github.com/sytpb/chatgpt-wework-robot/assets/35788274/80311beb-88a8-44e2-a5b1-25415e333d84">
<img width="1027" alt="Screen Shot 2023-06-14 at 10 00 38 AM" src="https://github.com/sytpb/chatgpt-wework-robot/assets/35788274/8b81b0ec-8b85-42f6-ac8c-754e087eb9c3">

**Comment by sytpb** [comment]
这是哪里发出来的？

**Comment by zapp926** [comment]
> 这是哪里发出来的？

就是企业微信客户端添加应用，给机器人应用发消息，没有收到任何的回复。连「正在生成回答」也没有出现。Log地方也看不到任何的消息，没有与GPT 3.5建立对话，不清楚是不是「可信IP」问题，还是证书问题。

**Comment by sytpb** [comment]
不知道你这啥情况，你得调试一下了，可信ip 保存成功就可以了， 域名能ping通？ 浏览器里访问一下，看下日志有没有。

**Comment by sytpb** [comment]
如果找到原因，请把问题和解决方法贴上来。有其他疑问，也可以继续提出来。

**Comment by zapp926** [comment]
> 不知道你这啥情况，你得调试一下了，可信ip 保存成功就可以了， 域名能ping通？ 浏览器里访问一下，看下日志有没有。

好的，我再研究一下，谢谢。通过CNAME转的域名，不加「/message」是可以ping通的。浏览器访问没有日志出现。

等研究通了，我来回复解决方法。

**Comment by zapp926** [comment]
> 不知道你这啥情况，你得调试一下了，可信ip 保存成功就可以了， 域名能ping通？ 浏览器里访问一下，看下日志有没有。

浏览器直接访问【render生成的域名链接 + message】，出现「urlSetting Error!」的错误。感觉是这里的错误造成的。

[wework-chatgpt-zckl.onrender.com](https://wework-chatgpt-zckl.onrender.com/)

**Comment by sytpb** [comment]
这是正常的，这里说明你服务是可访问，这是企业微信验证url , 因为你无法模拟他的参数，所以验证不通过。问题是你的消息发出去，为什么服务端收不到。

**Comment by sytpb** [comment]
url 设置保存提示成功了吗？

**Comment by zapp926** [comment]
> url 设置保存提示成功了吗？

是的，URL设置保存是成功的，这块没有问题。

可能还是【可信IP】的问题，「可信IP」因为我们企业微信经过企业认证，有自己的企业服务器。

所以是将render上的三个IP地址，转为我们公司自己的服务器IP。大概率就是这步出现的问题。

**Comment by sytpb** [comment]
是怎么转的？ 服务部署在哪，不是部署在render 上吗？

**Comment by zapp926** [comment]
现在问题解决了。

服务是部署在render上，因为我们公司企业微信有自己的服务器，所以可信IP部分配置是没有通过的。

所以现在的请求是企业微信请求的消息，先到我们公司自己的域名上，可信IP部分配置的也是我们公司自己的服务器IP。

我们自己的服务器收到消息之后，再中转传给Render的链接。拿到GPT返回的消息之后，也是先将返回消息传给我们自己的公司服务器，再传给企业微信。

找技术同事研究了下代码，发现是GPT返回的结果，直接传给了「企业微信」，所以接收失败。改了下面这两个部分。
【comm/message.js 和 chat\text.js】https://qyapi.weixin.qq.com/cgi-bin 改成：https://公司域名/cgi-bin
