### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by cxhjmfl** [sytpb/chatgpt-wework-robot#3]
Apr 24 07:24:33 PM  ==> Starting service with 'node app.js'
Apr 24 07:24:37 PM  file:///opt/render/project/src/comm/debug.js:10
Apr 24 07:24:37 PM        Error.captureStackTrace(err, arguments.callee.caller);
Apr 24 07:24:37 PM                                               ^
Apr 24 07:24:37 PM  
Apr 24 07:24:37 PM  [get (file:///opt/render/project/src/comm/debug.js:10:46),get (file:///opt/render/project/src/comm/debug.js:29:18),Function.log (file:///opt/render/project/src/comm/debug.js:40:25),file:///opt/render/project/src/route/conversation.js:7:7,ModuleJob.run (internal/modules/esm/module_job.js:152:23),async Loader.import (internal/modules/esm/loader.js:177:24),async Object.loadESM (internal/process/esm_loader.js:68:5)]

**Comment by sytpb** [comment]
哦，正在调试新版本，等我这里通知啊。

**Comment by cxhjmfl** [comment]
OK 谢谢

**Comment by sytpb** [comment]
现在好了，可以部署了。
