### ISSUE TITLE
openapi回调地址请求不通过，多次重新Manual deploy都不行。

### ISSUE THREAD

**Issue by xianglinkong** [sytpb/chatgpt-wework-robot#7]
出不来your service is live.
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/70635358/234492135-eaafa420-1f15-4f78-b47d-81a6d791ac81.png">

**Comment by alovin** [comment]
遇到了同样的问题

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/234506495-f53fb536-3e41-4930-bf14-cf2f1f85bc52.png)
 往下拉 一下，没有吗。
看这状态，你这服务已经成功了。 进入应用， 发消息看下，gpt是否工作正常。

**Comment by alovin** [comment]
完成后复制生成的服务的URL，如下图，然后拷贝URL后面拼接上/message, 比如URL是 https://abc.com/ 拼接成 [https://abc.com/message，](https://abc.com/message%EF%BC%8C) 粘贴到上面第二步页面里，然后点保存. —— URL后缀给忘记了，加上“/message”就可以了

**Comment by xianglinkong** [comment]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/70635358/234507813-809fd519-2f20-47ef-aa3b-31947e4d81fe.png">

openapi回调地址请求不通过，无法保存。

**Comment by alovin** [comment]
> 

你的引用网址怎么和官方的不一样呢，主域名不应该是render.com的吗

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/234509952-83891f03-e88a-4562-b458-f5438e001680.png)
这是哪里来的？ url

**Comment by xianglinkong** [comment]
解决了，虽然是自定义的域名，仍然需要添加s，https，因为这个导致回调地址不通过。
