### ISSUE TITLE
正常运行后，不返回回复

### ISSUE THREAD

**Issue by alovin** [sytpb/chatgpt-wework-robot#8]
![image](https://user-images.githubusercontent.com/41071313/234511578-e3164839-c6fa-4ed6-9621-75a789be1fa5.png)
可以在后台的日志窗口的看到，已经得到了回复，但是微信端就一直没有回复。是不是我哪里配制错了？

**Comment by sytpb** [comment]
这很奇怪，检查下日志，看下有何异常。

**Comment by alovin** [comment]
> 这很奇怪，检查下日志，看下有何异常。

我又手动部署了一下，然后它自己就好了。

**Comment by alovin** [comment]
非常感谢！！！

**Comment by sytpb** [comment]
good
