### ISSUE TITLE
聊天框输出文本时url编码混乱

### ISSUE THREAD

**Issue by Tsunamicloud** [sytpb/chatgpt-wework-robot#9]
answer在传输过程中编码出现混乱
```%21```没有被解码为```!```
本例中，控制台输出的answer是正常的```!```，而企业微信中，中文回答成功输出了```!```，英文回答错误地输出了```%21```

![FC2$R WJA7`2EDKPE@M4NSG](https://user-images.githubusercontent.com/115339638/234652025-ba5d91fa-0c67-4eb1-b6e9-1d4802bee910.png)
![17$X8LX XSWV7WTX)$YIS%B](https://user-images.githubusercontent.com/115339638/234652063-48645139-80b0-480d-9627-3582f3cee2ff.png)
![{4IYE3(L41% 3D MNW}{7A](https://user-images.githubusercontent.com/115339638/234652082-1cded163-2f3c-4e1e-9d25-f4187c79c535.png)

**Comment by sytpb** [comment]
是的，这个需要优化一下，感觉微信端将内容做urlencode.

**Comment by sytpb** [comment]
最新版本已修复此问题！
